server:
  port: 8080
  shutdown: graceful # switch to a graceful mode
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: greeting-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # default is 30s

management:
  endpoints: # exposing the health Actuator endpoint
    web:
    exposure:
      include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
